### ISSUE TITLE
Importing from ui and ui-widgets standalone throws i18n error

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#142] opened 2020-06-04 11:56 UTC
When importing components standalone from `ui` or importing `Transfer` from `ui-widgets`, an i18n error is thrown.
Live example: https://codesandbox.io/s/ui-import-issue-vepmo

- ✅  `import { Button } from "@dhis2/ui-core"` works 
- ❌  `import { Button } from "@dhis2/ui"` doesn't work 
- ❌  `import { Transfer } from "@dhis2/ui"` doesn't work 
- ❌  `import { Transfer } from "@dhis2/ui-widgets"` doesn't work 

--------

_Screenshot from error:_
![image](https://user-images.githubusercontent.com/12590483/83753727-17d88a00-a66b-11ea-9b00-073fc8f1cbad.png)

**Comment by HendrikThePendric** [comment] 2020-06-04 12:44
Just a small note: this appears to only be happening in the code-sandbox environment. I've used the exact same code in a fresh CRA locally and couldn't reproduce it there.

**Comment by amcgee** [comment] 2020-06-04 13:56
No idea why, but the issue is that i18next isn’t applying the defaults on [this line](https://github.com/i18next/i18next/blob/master/src/i18next.js#L44) (or the compiled output of that line)

Might have something to do with in-browser module instantiation

**Comment by varl** [comment] 2020-11-12 13:22
Closing. Re-report in JIRA when this becomes important.

**Closed by varl** 2020-11-12 13:22 UTC
Labels: bug
